import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NgModule } from '@angular/core';
import { HttpModule } from '@angular/http';
import { HttpClientModule } from '@angular/common/http';
import { RouterModule } from '@angular/router';
import { FlexLayoutModule } from '@angular/flex-layout';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';


import { AppRoutingModule } from './app.routing';
import { ComponentsModule } from './modules/admin/components/components.module';

import { AppComponent } from './app.component';
import { MyOwnCustomMaterialModule } from './app.material.module';

import {
  AgmCoreModule
} from '@agm/core';
import { AdminLayoutComponent } from './modules/admin/layouts/admin-layout/admin-layout.component';
import { MainComponent } from './components/main/main.component';
import { LoginComponent } from './components/login/login.component';
import { RegistryComponent } from './components/registry/registry.component';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';
import { RecaptchaModule } from 'ng-recaptcha';
import { NgImageSliderModule } from 'ng-image-slider';
import { AngularEditorModule } from '@kolkov/angular-editor';
// import { OwlModule } from 'ngx-owl-carousel';

import { StoreModule } from '@ngrx/store';
import { appReducer } from './redux/app';
import { StoreDevtoolsModule } from '@ngrx/store-devtools';
import { environment } from 'environments/environment';

@NgModule({
  imports: [
    HttpClientModule,
    BrowserAnimationsModule,
    HttpModule,
    ComponentsModule,
    RouterModule,
    FormsModule,
    ReactiveFormsModule,
    AppRoutingModule,
    RecaptchaModule,
    // OwlModule,
    NgImageSliderModule,
    AngularEditorModule,
    FlexLayoutModule,
    MyOwnCustomMaterialModule,
    AgmCoreModule.forRoot({
      apiKey: 'YOUR_GOOGLE_MAPS_API_KEY'
    }),

    StoreModule.forRoot({ name: appReducer }),
    StoreDevtoolsModule.instrument({
      maxAge: 25, // Retains last 25 states
      logOnly: environment.production, // Restrict extension to log-only mode
    }),

  ],
  declarations: [
    AppComponent,
    AdminLayoutComponent,
    MainComponent,
    LoginComponent,
    RegistryComponent,
    AutoGeneratedComponent,
  ],
  providers: [
    // {
    //   provide: LOCALE_ID,
    //   useValue: 'es'
    // }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
